apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    type: application
    app: offer-calculator-web
  name: offer-calculator-web
  namespace: offer-calculator
data:
  application.properties: |-
    server.port=8080
    management.server.port=8090
    
    spring.jpa.hibernate.ddl-auto=update

    spring.datasource.url={{ .Values.database.url }}
    spring.datasource.username={{ .Values.database.user }}
    spring.datasource.password={{ .Values.database.password }}
