apiVersion: v1
kind: Service
metadata:
  labels:
    type: application
    app: offer-calculator-web
  name: offer-calculator-web
  namespace: offer-calculator
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: offer-calculator-web
  type: ClusterIP
status:
  loadBalancer: {}
