apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: application
    app: offer-calculator-view
  name: offer-calculator-view
  namespace: offer-calculator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: offer-calculator-view
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: application
        app: offer-calculator-view
    spec:
      containers:
      - image: offer-calculator-view:latest
        imagePullPolicy: IfNotPresent
        name: offer-calculator-view
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
